version: '3.8'
services:
  webapp6:
    image: alvaro3517/webapp6  
    container_name: webapp6
    ports:
      - "443:8443"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/globalmart
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234password?
    depends_on:
      - db
    restart: always
  

  db:
    image: mysql:8.3.0
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=1234password?
      - MYSQL_DATABASE=globalmart
    ports:
      - "3307:3306"

